# This action compiles only the different variants of CPU and GPU.
#
# It does not run tests since the workers are CPU-only Virtual Machines. 
# To enable GPU tests it would have to build a GPU version and run it on 
# an external Github worker in some other cloud.

name: Compile-only CPU, GPU and CPU-GPU variants 

on:
  push:
    branches: [ master, develop, github-actions-gpu ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: 'Build with ${{ matrix.cuda_option }}'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cuda_option: ['cuda=0 cpu=1', 'cuda=1 cpu=0', 'cuda=1 cpu=1']
        full_double: ['full_double=0', 'full_double=1']

    steps:
    - uses: actions/checkout@v2
    - name: get packages
      run: sudo apt install -y gfortran liblapack-dev libblas-dev python3.9 linux-headers-$(uname -r) nvidia-cuda-toolkit
    - name: configure
      run: ./configure
    - name: make ${{ matrix.cuda_option }}
      run: make -j ${{ matrix.cuda_option}}
