# This action runs a linter in the codebase.
#
# From https://github.com/github/super-linter, it runs a VM that checks all the code
# for code formatting style consistency.
name: Lint Code Base

on:
  pull_request:
    branches: [master, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# super-linter needs read access to the code and write access to commit
# statuses; nothing more.
permissions:
  contents: read
  statuses: write

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
          # https://github.com/github/super-linter#environment-variables
          # We enable explicitly YAML so it doesn't check for anything else.
          # Only YAML should be .github/workflows.
          VALIDATE_YAML: true
          # TODO: Enable this when codebase is clang-format compliant.
          # VALIDATE_CPP: true
          # TODO: Enable this when codebase is autopep8 compliant.
          # VALIDATE_PYTHON: true
          # TODO: Enable this when codebase is bash-exec compliant.
          # VALIDATE_BASH: true 
          # VALIDATE_BASH_EXEC: true 
          # TODO: Enable this when codebase is chktex compliant.
          # VALIDATE_LATEX: true 
